### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mohamed82008** [StanJulia/CmdStan.jl#69]
Hi,

Can we please get a new release with the updated Compat section?

**Comment by goedman** [comment]
Hi, can you let me know what the issue is? I am working though the MCMCChains update, but just wondering if there is another problem.

Best,
Rob

**Comment by mohamed82008** [comment]
I am trying to fix https://github.com/TuringLang/Turing.jl/runs/338443995#step:4:254 and I think one fix could be a new release here. Removing the explicit requirement on BinDeps could be another fix but I am not sure where that is.

**Comment by goedman** [comment]
I’ll certainly keep your other fixes, but do you use Homebrew to install cmdstan? The dependency is in the build.jl file in /deps. Although BinDeps is now on a major version 1 (hence it will give fewer work/problems with version updates), this option has been disabled long enough with no one complaining, that I feel fairly save to remove it.

**Comment by goedman** [comment]
I've just put in a request to merge without the BinDeps dependency. If you would like that back, I'll add it back in. Apologies it took so long, it was pretty late yesterday evening when I responded.

**Comment by goedman** [comment]
In the end I merged your full PR into v5.3.0. Maybe I'll drop BinDeps and Homebrew in a few weeks.

**Comment by goedman** [comment]
I'll remove that dependency anyway. I think there is a problem with Homebrew (OSX only, v0.6.4.) and BinDeps 1.0.

By the way, if you would like that, I have no problem giving you access rights to CmdStan.

**Comment by mohamed82008** [comment]
So it seems that the release didn't solve the issue in Turing, I will look into why. Thanks for going through with it though. We don't use Homebrew directly in Turing no.
